version: 2

models:
  - name: per_day_view
    description: "Dữ liệu theo ngày từ các dự án"
    meta:
      metrics:
        - name: tap_chip
          label: "Total Tap Chip"
          description: "Tổng số lượng tap chip"
          type: sum
          sql: tap_chip

        - name: memories
          label: "Total Memories"
          description: "Tổng số lượng memories"
          type: sum
          sql: memories

        - name: rewards
          label: "Total Rewards"
          description: "Tổng số lượng rewards"
          type: sum
          sql: rewards

    columns:
      - name: time
        description: "Ngày"
        tests:
          - not_null
        meta:
          dimension:
            type: timestamp
            time_intervals: ["day"] # Chỉ group theo ngày

      - name: project_name
        description: "Tên dự án"
        tests:
          - not_null
        meta:
          dimension:
            type: string

      - name: tap_chip
        description: "Số lượng tap chip"
        tests:
          - not_null

      - name: memories
        description: "Số lượng memories"
        tests:
          - not_null

      - name: rewards
        description: "Số lượng rewards"
        tests:
          - not_null

  - name: per_hour_view
    description: "Dữ liệu theo giờ từ các dự án"
    meta:
      metrics:
        - name: tap_chip
          label: "Total Tap Chip"
          description: "Tổng số lượng tap chip"
          type: sum
          sql: tap_chip

        - name: memories
          label: "Total Memories"
          description: "Tổng số lượng memories"
          type: sum
          sql: memories

        - name: rewards
          label: "Total Rewards"
          description: "Tổng số lượng rewards"
          type: sum
          sql: rewards

    columns:
      - name: time
        description: "Thời điểm (timestamp)"
        tests:
          - not_null
        meta:
          dimension:
            type: timestamp
            time_intervals: ["hour"] # Chỉ group theo giờ

      - name: project_name
        description: "Tên dự án"
        tests:
          - not_null
        meta:
          dimension:
            type: string

      - name: tap_chip
        description: "Số lượng tap chip"
        tests:
          - not_null

      - name: memories
        description: "Số lượng memories"
        tests:
          - not_null

      - name: rewards
        description: "Số lượng rewards"
        tests:
          - not_null

  - name: per_month_view
    description: "Dữ liệu theo tháng từ các dự án"
    meta:
      metrics:
        - name: tap_chip
          label: "Total Tap Chip"
          description: "Tổng số lượng tap chip"
          type: sum
          sql: tap_chip

        - name: memories
          label: "Total Memories"
          description: "Tổng số lượng memories"
          type: sum
          sql: memories

        - name: rewards
          label: "Total Rewards"
          description: "Tổng số lượng rewards"
          type: sum
          sql: rewards

    columns:
      - name: time
        description: "Tháng"
        tests:
          - not_null
        meta:
          dimension:
            type: timestamp
            time_intervals: ["month", "quarter", "year"] # Group theo tháng, quý, năm

      - name: project_name
        description: "Tên dự án"
        tests:
          - not_null
        meta:
          dimension:
            type: string

      - name: tap_chip
        description: "Số lượng tap chip"
        tests:
          - not_null

      - name: memories
        description: "Số lượng memories"
        tests:
          - not_null

      - name: rewards
        description: "Số lượng rewards"
        tests:
          - not_null

  - name: behavior_per_hour_view
    description: "Chip theo giờ"
    meta:
      metrics:
        - name: counting_sum
          label: "Total Counting"
          description: "Tổng số lượng"
          type: sum
          sql: counting

        - name: counting_average
          label: "Average Counting"
          description: "Trung bình số lượng"
          type: average
          sql: counting

    columns:
      - name: time
        description: "Thời điểm (timestamp)"
        tests:
          - not_null
        meta:
          dimension:
            type: timestamp
            time_intervals: ["hour"] # Chỉ group theo giờ

      - name: type
        description: "Loại chip"
        tests:
          - not_null
        meta:
          dimension:
            type: string

      - name: project_id
        description: "ID dự án"
        tests:
          - not_null

      - name: project_name
        description: "Tên dự án"
        tests:
          - not_null

      - name: category
        description: "Danh mục"

      - name: counting
        description: "Số lượng"
        tests:
          - not_null
sources:
  - name: public
    description: "Schema public from etl_db"
    database: etl_db
    tables:
      - name: per_hour
        description: "Dữ liệu theo giờ từ các dự án"
        columns:
          - name: timestamp
            description: "Thời điểm (timestamp)"
          - name: project_name
            description: "Tên dự án"
          - name: tap_chip
            description: "Số lượng tap chip"
          - name: memories
            description: "Số lượng memories"
          - name: rewards
            description: "Số lượng rewards"
      - name: per_day
        description: "Dữ liệu theo ngày từ các dự án"
        columns:
          - name: timestamp
            description: "Thời điểm (timestamp)"
          - name: project_name
            description: "Tên dự án"
          - name: tap_chip
            description: "Số lượng tap chip"
          - name: memories
            description: "Số lượng memories"
          - name: rewards
            description: "Số lượng rewards"
      - name: per_month
        description: "Dữ liệu theo tháng từ các dự án"
        columns:
          - name: timestamp
            description: "Thời điểm (timestamp)"
          - name: project_name
            description: "Tên dự án"
          - name: tap_chip
            description: "Số lượng tap chip"
          - name: memories
            description: "Số lượng memories"
          - name: rewards
            description: "Số lượng rewards"
      - name: behavior_per_hour
        description: "Chip theo giờ"
        columns:
          - name: timestamp
            description: "Thời điểm (timestamp)"
          - name: type
            description: "Loại chip"
          - name: project_id
            description: "ID dự án"
          - name: project_name
            description: "Tên dự án"
          - name: category
            description: "Danh mục"
          - name: counting
            description: "Số lượng"
